### ISSUE TITLE
Why so angry?

### ISSUE THREAD

**Issue by sebastienros** [atifaziz/AngryArrays#8]

**Comment by atifaziz** [comment]
LOL. Well, that's what happens when you have to come up with silly project names to avoid conflicts. I felt [Arrays](https://www.nuget.org/packages/Arrays) would have been pompous. Lacking further imagination, and if I'm recalling right, I think Angry Arrays came from my initials (AA). Anyway, I am not sure you were looking for an explanation. 😉
